# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WOLVERINE 2021

navbar-links:
  About: "about"
  Call for Participation: "call"
  Interactive Program: "program"
  Organizing Team: "team"

avatar: "/resources/logo2.png"
round-avatar: false

# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  input: GFM  #Github Flavored Markdown
remote_theme:  daattali/beautiful-jekyll 
paginate: 5

navbar-col: "#b11170"
navbar-text-col: "#f3e343"
link-col: "#b11170"
hover-col: "#da9851"
footer-text-col: "#f3e343"
footer-link-col: "#404040"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  # - jemoji
  - jekyll-spaceship
#  - gemoji

#Gemoji plugin settings
#emoji_dir: "/sachingpta.gitlab.io/assets/images/emoji"
  

# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
